version: '3.8'

services:
  web:
    build: .
    container_name: volta_vintage_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/vintage_bulb_db
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7-jammy
    container_name: volta_vintage_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
